---
:backends: yaml
:yaml:
    :datadir: '/vagrant/puphpet/boxes/hiera'
:hierarchy:
    - app_data
    - php_data
    - nginx_data
    - hhvm_data
    - common_data
:merge_behavior: deeper
:logger: console
...